# Generated by Django 4.1.2 on 2022-10-13 02:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article", name="body", field=ckeditor.fields.RichTextField(),
        ),
    ]
